export enum RANDOM_JSON_TYPES{
    FETCH_RANDOM_JSON_FAILED='json/FETCH_RANDOM_JSON_FAILED',
    FETCH_RANDOM_JSON_LOADING='json/FETCH_RANDOM_JSON_LOADING',
    FETCH_RANDOM_JSON_SUCCESS='json/FETCH_RANDOM_JSON_SUCCESS',
}

export type RandomJsonType={
    payload:[];
}